/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./app/**/*.{js,jsx,ts,tsx}', './components/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        'on-tertiary-fixed-variant': '#474649',
        'on-surface': '#e2e2e2',
        'surface-container-low': '#1b1b1b',
        'tertiary-container': '#cac8ca',
        'inverse-on-surface': '#303030',
        'on-secondary-fixed-variant': '#454747',
        'surface-container': '#1f1f1f',
        'inverse-surface': '#e2e2e2',
        'secondary-fixed': '#e2e2e2',
        'surface-variant': '#353535',
        outline: '#859585',
        'inverse-primary': '#006d35',
        'surface-container-high': '#2a2a2a',
        'on-primary-fixed-variant': '#005226',
        background: '#131313',
        surface: '#131313',
        'tertiary-fixed': '#e4e2e4',
        'surface-tint': '#00e475',
        'on-tertiary-container': '#545356',
        'on-surface-variant': '#bacbb9',
        'on-secondary-fixed': '#1a1c1c',
        'on-background': '#e2e2e2',
        'on-secondary-container': '#b4b5b5',
        primary: '#75ff9e',
        'secondary-fixed-dim': '#c6c6c7',
        'tertiary-fixed-dim': '#c8c6c8',
        'on-error-container': '#ffdad6',
        'on-tertiary-fixed': '#1b1b1d',
        'on-secondary': '#2f3131',
        'surface-container-lowest': '#0e0e0e',
        'on-error': '#690005',
        'on-tertiary': '#303032',
        secondary: '#c6c6c7',
        'secondary-container': '#454747',
        'primary-container': '#00e676',
        'surface-container-highest': '#353535',
        'on-primary-container': '#00612e',
        'primary-fixed-dim': '#00e475',
        'surface-bright': '#393939',
        tertiary: '#e7e4e6',
        error: '#ffb4ab',
        'surface-dim': '#131313',
        'primary-fixed': '#62ff96',
        'on-primary': '#003918',
        'on-primary-fixed': '#00210b',
        'outline-variant': '#3b4a3d',
        'error-container': '#93000a',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        lg: '0.75rem',
        xl: '1rem',
        full: '9999px',
      },
      spacing: {
        'stack-sm': '8px',
        'margin-desktop': '40px',
        unit: '4px',
        'margin-mobile': '16px',
        'stack-lg': '32px',
        'stack-md': '16px',
        gutter: '24px',
      },
    },
  },
  plugins: [],
};
